#include "adc.h"

void ADC_Init(void)
{
   ADC2_DeInit();
   
   GPIO_Init( GPIOD, GPIO_PIN_3, GPIO_MODE_IN_FL_NO_IT  );
   
#if CONVERSIONMODE ==CONVERSIONMODE_SINGLE
   ADC2_Init(ADC2_CONVERSIONMODE_SINGLE , ADC2_CHANNEL_4, ADC2_PRESSEL_FCPU_D18,\
   ADC2_EXTTRIG_TIM, DISABLE, ADC2_ALIGN_RIGHT, ADC2_SCHMITTTRIG_CHANNEL10,ENABLE);
   ADC2_ITConfig(ENABLE);
   
#elif CONVERSIONMODE ==CONVERSIONMODE_CONTINUOUS
   ADC2_Init(ADC2_CONVERSIONMODE_CONTINUOUS , ADC2_CHANNEL_10, ADC2_PRESSEL_FCPU_D18,\
   ADC2_EXTTRIG_TIM, DISABLE, ADC2_ALIGN_RIGHT, ADC2_SCHMITTTRIG_CHANNEL10,DISABLE);
   ADC2_ITConfig(DISABLE);
#endif
   
   ADC2_Cmd(ENABLE);
   ADC2_StartConversion();
}
